{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":46092,"status":"ok","timestamp":1698866525504,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"JmOikfMp5HQb","outputId":"6cbbc6f7-e577-4933-dac2-1651237cc731"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive', force_remount=True)"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":169,"status":"ok","timestamp":1698866527675,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"ViFcYSgLAbZ8"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-13-51acec293ac9\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Moths!/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-13-51acec293ac9\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Moths!/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-13-51acec293ac9\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Moths!/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["cd /content/drive/MyDrive/Moths!/"]},{"cell_type":"markdown","metadata":{"id":"7Y7TvyPOtmK9"},"source":["Edit the `commit_message` variable and then click Runtime \u003e Restart and run all"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":9978,"status":"ok","timestamp":1698866539785,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"t_XgSG6zObXY","outputId":"80a0be96-ddbf-4d8a-c5d1-6efb322a16ec"},"outputs":[{"name":"stdout","output_type":"stream","text":["Refresh index: 100% (10/10), done.\n","On branch main\n","Your branch is up to date with 'origin/main'.\n","\n","Changes not staged for commit:\n","  (use \"git add \u003cfile\u003e...\" to update what will be committed)\n","  (use \"git restore \u003cfile\u003e...\" to discard changes in working directory)\n","\t\u001b[31mmodified:   code/climatic_analysis.ipynb\u001b[m\n","\t\u001b[31mmodified:   github_scripts/charles_github.ipynb\u001b[m\n","\n","Untracked files:\n","  (use \"git add \u003cfile\u003e...\" to include in what will be committed)\n","\t\u001b[31mcode/biodiversity.ipynb\u001b[m\n","\t\u001b[31mdata/gadm41_USA_shp/\u001b[m\n","\t\u001b[31mdocuments/Pre-proj-team15.gdoc\u001b[m\n","\t\u001b[31mdocuments/Prog-proj-team15.gdoc\u001b[m\n","\t\u001b[31mdocuments/notes.gdoc\u001b[m\n","\n","no changes added to commit (use \"git add\" and/or \"git commit -a\")\n"]}],"source":["!git status"]},{"cell_type":"code","execution_count":4,"metadata":{"executionInfo":{"elapsed":205,"status":"ok","timestamp":1698866557435,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"C6sRutK95cCs"},"outputs":[],"source":["# **Edit this each time to determine what I am going to commit and comment on what you are changing**\n","\n","files = \"github_scripts/charles_github.ipynb data/mantodea_ca_gbif_simple.csv\"\n","commit_message = \"okay, I think I finally found how to download the data. going to delete my notes next and clean it up for all links. to see the data available navigate to a catalog page like this: https://thredds.daac.ornl.gov/thredds/catalog/ornldaac/2131/catalog.html\"\n","\n"]},{"cell_type":"code","execution_count":5,"metadata":{"executionInfo":{"elapsed":1,"status":"ok","timestamp":1698866560332,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"KTfsK7ke1SjP"},"outputs":[],"source":["# Edit this once so that the changes are linked to you\n","\n","username = \"CharlesLehnen\"\n","email = \"lehnen@usc.edu\""]},{"cell_type":"code","execution_count":6,"metadata":{"executionInfo":{"elapsed":573,"status":"ok","timestamp":1698866561751,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"IR22uwPCIYXu"},"outputs":[],"source":["with open('/content/drive/MyDrive/github_token.txt', 'r') as file:\n","    git_token = file.readline().strip()\n","\n","repository = \"DSCI_550_Final_Project\"\n","\n","!git config --global user.email \"$email\"\n","!git config --global user.name \"$username\""]},{"cell_type":"code","execution_count":7,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1422,"status":"ok","timestamp":1698866565960,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"xd0o8poG021Z","outputId":"2abd76c1-65e9-4e24-f2cd-fe70ad4d44f7"},"outputs":[{"name":"stdout","output_type":"stream","text":["Hook already exists: post-merge\n","\n","\t#!/bin/sh\n","\tcommand -v git-lfs \u003e/dev/null 2\u003e\u00261 || { echo \u003e\u00262 \"\\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-merge' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\\n\"; exit 2; }\n","\tgit lfs post-merge \"$@\"\n","\n","To resolve this, either:\n","  1: run `git lfs update --manual` for instructions on how to merge hooks.\n","  2: run `git lfs update --force` to overwrite your hook.\n"]}],"source":["# Initialize GIT LFS\n","\n","!git lfs install\n","!git add .gitattributes"]},{"cell_type":"code","execution_count":8,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":17985,"status":"ok","timestamp":1698866586252,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"a9sXlwTABKG_","outputId":"5b9cbdc0-6232-439e-e2bd-de13297bd5e9"},"outputs":[{"name":"stdout","output_type":"stream","text":["[main cdd51b8] at least made progress on adding CA in climatic_analysis\n"," 18 files changed, 9 insertions(+), 2 deletions(-)\n"," create mode 100644 code/biodiversity.ipynb\n"," rewrite code/climatic_analysis.ipynb (99%)\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_0.cpg\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_0.dbf\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_0.prj\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_0.shp\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_0.shx\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_1.cpg\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_1.dbf\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_1.prj\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_1.shp\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_1.shx\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_2.cpg\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_2.dbf\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_2.prj\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_2.shp\n"," create mode 100644 data/gadm41_USA_shp/gadm41_USA_2.shx\n"," rewrite github_scripts/charles_github.ipynb (98%)\n"]}],"source":["# disable post-commit hook for some reason\n","!mv .git/hooks/post-commit .git/hooks/post-commit.disabled\n","\n","# because gitignore of Google Drive files sometimes doesn't work\n","!git add -- ':!*.gdoc'\n","\n","!git commit -m \"$commit_message\""]},{"cell_type":"code","execution_count":13,"metadata":{"executionInfo":{"elapsed":164,"status":"ok","timestamp":1698349976255,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"4XcXhTISTJ5_"},"outputs":[],"source":["# If stuck and have to reset back to where Github online left off\n","\n","#!git fetch origin\n","#!gist reset --hard origin/main"]},{"cell_type":"code","execution_count":11,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":165,"status":"ok","timestamp":1698866620154,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"nrH38coKP7cA","outputId":"c6cc58d3-b1a9-48f4-86f1-414590140e08"},"outputs":[{"name":"stdout","output_type":"stream","text":["error: cannot pull with rebase: You have unstaged changes.\n","error: please commit or stash them.\n"]}],"source":["!git pull origin main"]},{"cell_type":"code","execution_count":10,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":11378,"status":"ok","timestamp":1698866617368,"user":{"displayName":"Charles Lehnen","userId":"06444957509463345570"},"user_tz":420},"id":"f4VmVEV3BLeH","outputId":"79ca089b-ae15-45b3-d106-ac04d29cc510"},"outputs":[{"name":"stdout","output_type":"stream","text":["Enumerating objects: 26, done.\n","Counting objects:   3% (1/26)\rCounting objects:   7% (2/26)\rCounting objects:  11% (3/26)\rCounting objects:  15% (4/26)\rCounting objects:  19% (5/26)\rCounting objects:  23% (6/26)\rCounting objects:  26% (7/26)\rCounting objects:  30% (8/26)\rCounting objects:  34% (9/26)\rCounting objects:  38% (10/26)\rCounting objects:  42% (11/26)\rCounting objects:  46% (12/26)\rCounting objects:  50% (13/26)\rCounting objects:  53% (14/26)\rCounting objects:  57% (15/26)\rCounting objects:  61% (16/26)\rCounting objects:  65% (17/26)\rCounting objects:  69% (18/26)\rCounting objects:  73% (19/26)\rCounting objects:  76% (20/26)\rCounting objects:  80% (21/26)\rCounting objects:  84% (22/26)\rCounting objects:  88% (23/26)\rCounting objects:  92% (24/26)\rCounting objects:  96% (25/26)\rCounting objects: 100% (26/26)\rCounting objects: 100% (26/26), done.\n","Delta compression using up to 2 threads\n","Compressing objects: 100% (18/18), done.\n","Writing objects: 100% (20/20), 19.69 MiB | 3.48 MiB/s, done.\n","Total 20 (delta 5), reused 0 (delta 0), pack-reused 0\n","remote: Resolving deltas: 100% (5/5), completed with 2 local objects.\u001b[K\n","To https://github.com/CharlesLehnen/DSCI_550_Final_Project.git\n","   bb5e2c9..cdd51b8  main -\u003e main\n"]}],"source":["# disable pre-push hook for some reason\n","!mv .git/hooks/pre-push .git/hooks/pre-push.disabled\n","\n","# To increase hang\n","!git config http.postBuffer 524288000\n","\n","!git remote set-url origin https://{git_token}@github.com/{username}/{repository}.git\n","!git push origin main"]}],"metadata":{"colab":{"authorship_tag":"ABX9TyPJ1QSp8rgpbrjGoPTpuMp3","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}